#### POST http://localhost:8080/usuarios ==> Cria um novo usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "data": {
    "email": "Giovana@email.com",
    "senha": "senha123@A",
    "nome": "Giovana Silva",
    "cpf": "21342678245"
  }
}

#### POST http://localhost:8080/usuarios/login ==> Faz login de um usuário

POST http://localhost:8080/usuarios/login
Content-Type: application/json

{
  "data":{
    "email": "Giovana@email.com",
    "senha": "senha123@A"
  }
}
#### Get http://localhost:8080/usuarios/idDoUsuario ==> Busca por um usuário por meio do seu id e retorna todos os carrinhos os que foram fechados e os que estão abertos

GET http://localhost:8080/usuarios/1efdc144-948e-40a3-8839-7d943ea4d130


#### POST http://localhost:8080/produtos ==> Cria um novo produto e adiciona no carrinho
POST http://localhost:8080/produtos
Content-Type: application/json

{
  "data": {
    "nome": "Copo byron",
    "descricao": "Copo top",
    "preco": 89.99,
    "categoria": "copo",
    "quantidadeDisponivel": 10
  }
}

#### GET http://localhost:8080/produtos ==> Busca todos os produtos cadastrados

GET http://localhost:8080/produtos

#### POST http://localhost:8080/produtos/carrinho ==> Adiciona um produto a um carrinho

POST http://localhost:8080/carrinho
Content-Type: application/json

{
  "data": {
    "produtoId": 6,
    "usuarioId": 2
 
  }
}

### DELETE http://localhost:8080/carrinho/usuarioId/produtoId ==> Deleta um produto de um carrinho
DELETE http://localhost:8080/carrinho/2/6


