#### POST http://localhost:8080/usuarios ==> Cria um novo usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "data": {
    "email": "pedro@email.com",
    "senha": "senha123",
    "nome": "Pedro Nogueira",
    "cpf": "22342678214"
  }
}

#### Get http://localhost:8080/usuarios/idDoUsuario ==> Busca por um usuário por meio do seu id e retorna todos os carrinhos os que foram fechados e os que estão abertos

GET http://localhost:8080/usuarios/1


#### POST http://localhost:8080/usuarios/idDoUsuario/carrinhos ==> Cria um novo carrinho para um usuário


#### POST http://localhost:8080/produtos ==> Cria um novo produto
POST http://localhost:8080/produtos
Content-Type: application/json

{
  "data": {
    "nome": "Camisa Byron",
    "descricao": "Camisa muito linda",
    "preco": 75.0,
    "categoria": "objeto",
    "quantidadeDisponivel": 20
  }
}

#### GET http://localhost:8080/produtos ==> Busca todos os produtos cadastrados

GET http://localhost:8080/produtos

#### POST http://localhost:8080/produtos/carrinho ==> Adiciona um produto a um carrinho

POST http://localhost:8080/carrinho
Content-Type: application/json

{
  "data": {
    "produtoId": 3,
    "usuarioId": 2
 
  }
}

#### DELETE http://localhost:8080/carrinho/idDoCarrinho ==> Deleta um produto de um carrinho

### DELETE http://localhost:8080/carrinho/remover/usuarioId/produtoId
DELETE http://localhost:8080/carrinho/2/3
