#### POST http://localhost:8080/usuarios ==> Cria um novo usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "data": {
    "email": "Eduardo@email.com",
    "senha": "senha123",
    "nome": "Eduardo",
    "cpf": "22342678234"
  }
}

#### Get http://localhost:8080/usuarios/idDoUsuario ==> Busca por um usuário por meio do seu id e retorna todos os carrinhos os que foram fechados e os que estão abertos

GET http://localhost:8080/usuarios/1
