name: Staging on Digital Ocean Droplet
run-name: ${{ github.actor }} is deploying to staging environment
on:
  workflow_dispatch:
  push:
    branches:
      - staging
jobs:
  ssh-into-droplet-and-deploy-changes:
    name: SSH into droplet and deploy changes
    runs-on: ubuntu-22.04
    steps:
      - name: SSH into droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{secrets.PASSWORD}}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /home/equipe-game-masters
            git checkout staging
            git pull
            docker compose down
            docker compose up -d --build --force-recreate --remove-orphans
